import type { Bot } from '@yeap/shared'

type Props = { bot_name: string; bots: Bot[]; size?: number }

export function BotAvatar({ bot_name, bots, size = 32 }: Props) {
  const bot = bots.find((b) => b.name === bot_name)

  if (!bot) {
    const initials = bot_name.slice(0, 2).toUpperCase()
    return (
      <span
        style={{
          width: size,
          height: size,
          borderRadius: '50%',
          background: '#475569',
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          fontSize: size * 0.4,
          fontWeight: 600,
          color: '#fff',
          flexShrink: 0,
        }}
      >
        {initials}
      </span>
    )
  }

  return (
    <span
      className="bot-avatar"
      style={{ width: size, height: size, display: 'inline-flex', flexShrink: 0, overflow: 'hidden' }}
      // svg_icon is always server-generated by generateBotIcon() — safe to inject
      dangerouslySetInnerHTML={{ __html: bot.svg_icon }}
    />
  )
}
